spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/shrioDemo?serverTimezone=Asia/Shanghai&useTimezone=true


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.wyy.demoshiro.entity
  configuration:
    map-underscore-to-camel-case: true